# Generated by Django 3.1.13 on 2021-12-21 17:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='link',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'jpeg', 'png', 'mp3', 'jpg'])]),
            preserve_default=False,
        ),
    ]
