# Generated by Django 3.1.13 on 2021-12-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndUser',
        ),
    ]
